/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Domain;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-05")
public class Ride implements org.apache.thrift.TBase<Ride, Ride._Fields>, java.io.Serializable, Cloneable, Comparable<Ride> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Ride");

  private static final org.apache.thrift.protocol.TField RIDE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("rideID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DESTINATION_FIELD_DESC = new org.apache.thrift.protocol.TField("destination", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("date", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField HOUR_FIELD_DESC = new org.apache.thrift.protocol.TField("hour", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField NR_SEATS_FIELD_DESC = new org.apache.thrift.protocol.TField("nrSeats", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RideStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RideTupleSchemeFactory();

  public int rideID; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String destination; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String date; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String hour; // required
  public int nrSeats; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RIDE_ID((short)1, "rideID"),
    DESTINATION((short)2, "destination"),
    DATE((short)3, "date"),
    HOUR((short)4, "hour"),
    NR_SEATS((short)5, "nrSeats");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RIDE_ID
          return RIDE_ID;
        case 2: // DESTINATION
          return DESTINATION;
        case 3: // DATE
          return DATE;
        case 4: // HOUR
          return HOUR;
        case 5: // NR_SEATS
          return NR_SEATS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RIDEID_ISSET_ID = 0;
  private static final int __NRSEATS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RIDE_ID, new org.apache.thrift.meta_data.FieldMetaData("rideID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DESTINATION, new org.apache.thrift.meta_data.FieldMetaData("destination", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATE, new org.apache.thrift.meta_data.FieldMetaData("date", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOUR, new org.apache.thrift.meta_data.FieldMetaData("hour", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NR_SEATS, new org.apache.thrift.meta_data.FieldMetaData("nrSeats", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Ride.class, metaDataMap);
  }

  public Ride() {
  }

  public Ride(
    int rideID,
    java.lang.String destination,
    java.lang.String date,
    java.lang.String hour,
    int nrSeats)
  {
    this();
    this.rideID = rideID;
    setRideIDIsSet(true);
    this.destination = destination;
    this.date = date;
    this.hour = hour;
    this.nrSeats = nrSeats;
    setNrSeatsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Ride(Ride other) {
    __isset_bitfield = other.__isset_bitfield;
    this.rideID = other.rideID;
    if (other.isSetDestination()) {
      this.destination = other.destination;
    }
    if (other.isSetDate()) {
      this.date = other.date;
    }
    if (other.isSetHour()) {
      this.hour = other.hour;
    }
    this.nrSeats = other.nrSeats;
  }

  public Ride deepCopy() {
    return new Ride(this);
  }

  @Override
  public void clear() {
    setRideIDIsSet(false);
    this.rideID = 0;
    this.destination = null;
    this.date = null;
    this.hour = null;
    setNrSeatsIsSet(false);
    this.nrSeats = 0;
  }

  public int getRideID() {
    return this.rideID;
  }

  public Ride setRideID(int rideID) {
    this.rideID = rideID;
    setRideIDIsSet(true);
    return this;
  }

  public void unsetRideID() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RIDEID_ISSET_ID);
  }

  /** Returns true if field rideID is set (has been assigned a value) and false otherwise */
  public boolean isSetRideID() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RIDEID_ISSET_ID);
  }

  public void setRideIDIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RIDEID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDestination() {
    return this.destination;
  }

  public Ride setDestination(@org.apache.thrift.annotation.Nullable java.lang.String destination) {
    this.destination = destination;
    return this;
  }

  public void unsetDestination() {
    this.destination = null;
  }

  /** Returns true if field destination is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination() {
    return this.destination != null;
  }

  public void setDestinationIsSet(boolean value) {
    if (!value) {
      this.destination = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDate() {
    return this.date;
  }

  public Ride setDate(@org.apache.thrift.annotation.Nullable java.lang.String date) {
    this.date = date;
    return this;
  }

  public void unsetDate() {
    this.date = null;
  }

  /** Returns true if field date is set (has been assigned a value) and false otherwise */
  public boolean isSetDate() {
    return this.date != null;
  }

  public void setDateIsSet(boolean value) {
    if (!value) {
      this.date = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHour() {
    return this.hour;
  }

  public Ride setHour(@org.apache.thrift.annotation.Nullable java.lang.String hour) {
    this.hour = hour;
    return this;
  }

  public void unsetHour() {
    this.hour = null;
  }

  /** Returns true if field hour is set (has been assigned a value) and false otherwise */
  public boolean isSetHour() {
    return this.hour != null;
  }

  public void setHourIsSet(boolean value) {
    if (!value) {
      this.hour = null;
    }
  }

  public int getNrSeats() {
    return this.nrSeats;
  }

  public Ride setNrSeats(int nrSeats) {
    this.nrSeats = nrSeats;
    setNrSeatsIsSet(true);
    return this;
  }

  public void unsetNrSeats() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NRSEATS_ISSET_ID);
  }

  /** Returns true if field nrSeats is set (has been assigned a value) and false otherwise */
  public boolean isSetNrSeats() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NRSEATS_ISSET_ID);
  }

  public void setNrSeatsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NRSEATS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RIDE_ID:
      if (value == null) {
        unsetRideID();
      } else {
        setRideID((java.lang.Integer)value);
      }
      break;

    case DESTINATION:
      if (value == null) {
        unsetDestination();
      } else {
        setDestination((java.lang.String)value);
      }
      break;

    case DATE:
      if (value == null) {
        unsetDate();
      } else {
        setDate((java.lang.String)value);
      }
      break;

    case HOUR:
      if (value == null) {
        unsetHour();
      } else {
        setHour((java.lang.String)value);
      }
      break;

    case NR_SEATS:
      if (value == null) {
        unsetNrSeats();
      } else {
        setNrSeats((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RIDE_ID:
      return getRideID();

    case DESTINATION:
      return getDestination();

    case DATE:
      return getDate();

    case HOUR:
      return getHour();

    case NR_SEATS:
      return getNrSeats();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RIDE_ID:
      return isSetRideID();
    case DESTINATION:
      return isSetDestination();
    case DATE:
      return isSetDate();
    case HOUR:
      return isSetHour();
    case NR_SEATS:
      return isSetNrSeats();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Ride)
      return this.equals((Ride)that);
    return false;
  }

  public boolean equals(Ride that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_rideID = true;
    boolean that_present_rideID = true;
    if (this_present_rideID || that_present_rideID) {
      if (!(this_present_rideID && that_present_rideID))
        return false;
      if (this.rideID != that.rideID)
        return false;
    }

    boolean this_present_destination = true && this.isSetDestination();
    boolean that_present_destination = true && that.isSetDestination();
    if (this_present_destination || that_present_destination) {
      if (!(this_present_destination && that_present_destination))
        return false;
      if (!this.destination.equals(that.destination))
        return false;
    }

    boolean this_present_date = true && this.isSetDate();
    boolean that_present_date = true && that.isSetDate();
    if (this_present_date || that_present_date) {
      if (!(this_present_date && that_present_date))
        return false;
      if (!this.date.equals(that.date))
        return false;
    }

    boolean this_present_hour = true && this.isSetHour();
    boolean that_present_hour = true && that.isSetHour();
    if (this_present_hour || that_present_hour) {
      if (!(this_present_hour && that_present_hour))
        return false;
      if (!this.hour.equals(that.hour))
        return false;
    }

    boolean this_present_nrSeats = true;
    boolean that_present_nrSeats = true;
    if (this_present_nrSeats || that_present_nrSeats) {
      if (!(this_present_nrSeats && that_present_nrSeats))
        return false;
      if (this.nrSeats != that.nrSeats)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + rideID;

    hashCode = hashCode * 8191 + ((isSetDestination()) ? 131071 : 524287);
    if (isSetDestination())
      hashCode = hashCode * 8191 + destination.hashCode();

    hashCode = hashCode * 8191 + ((isSetDate()) ? 131071 : 524287);
    if (isSetDate())
      hashCode = hashCode * 8191 + date.hashCode();

    hashCode = hashCode * 8191 + ((isSetHour()) ? 131071 : 524287);
    if (isSetHour())
      hashCode = hashCode * 8191 + hour.hashCode();

    hashCode = hashCode * 8191 + nrSeats;

    return hashCode;
  }

  @Override
  public int compareTo(Ride other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRideID()).compareTo(other.isSetRideID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRideID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rideID, other.rideID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDestination()).compareTo(other.isSetDestination());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination, other.destination);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDate()).compareTo(other.isSetDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.date, other.date);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHour()).compareTo(other.isSetHour());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHour()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hour, other.hour);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNrSeats()).compareTo(other.isSetNrSeats());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNrSeats()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nrSeats, other.nrSeats);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Ride(");
    boolean first = true;

    sb.append("rideID:");
    sb.append(this.rideID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("destination:");
    if (this.destination == null) {
      sb.append("null");
    } else {
      sb.append(this.destination);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("date:");
    if (this.date == null) {
      sb.append("null");
    } else {
      sb.append(this.date);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hour:");
    if (this.hour == null) {
      sb.append("null");
    } else {
      sb.append(this.hour);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nrSeats:");
    sb.append(this.nrSeats);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RideStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RideStandardScheme getScheme() {
      return new RideStandardScheme();
    }
  }

  private static class RideStandardScheme extends org.apache.thrift.scheme.StandardScheme<Ride> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Ride struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RIDE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.rideID = iprot.readI32();
              struct.setRideIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESTINATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destination = iprot.readString();
              struct.setDestinationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.date = iprot.readString();
              struct.setDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HOUR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hour = iprot.readString();
              struct.setHourIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // NR_SEATS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nrSeats = iprot.readI32();
              struct.setNrSeatsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Ride struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RIDE_ID_FIELD_DESC);
      oprot.writeI32(struct.rideID);
      oprot.writeFieldEnd();
      if (struct.destination != null) {
        oprot.writeFieldBegin(DESTINATION_FIELD_DESC);
        oprot.writeString(struct.destination);
        oprot.writeFieldEnd();
      }
      if (struct.date != null) {
        oprot.writeFieldBegin(DATE_FIELD_DESC);
        oprot.writeString(struct.date);
        oprot.writeFieldEnd();
      }
      if (struct.hour != null) {
        oprot.writeFieldBegin(HOUR_FIELD_DESC);
        oprot.writeString(struct.hour);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NR_SEATS_FIELD_DESC);
      oprot.writeI32(struct.nrSeats);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RideTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RideTupleScheme getScheme() {
      return new RideTupleScheme();
    }
  }

  private static class RideTupleScheme extends org.apache.thrift.scheme.TupleScheme<Ride> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Ride struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRideID()) {
        optionals.set(0);
      }
      if (struct.isSetDestination()) {
        optionals.set(1);
      }
      if (struct.isSetDate()) {
        optionals.set(2);
      }
      if (struct.isSetHour()) {
        optionals.set(3);
      }
      if (struct.isSetNrSeats()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetRideID()) {
        oprot.writeI32(struct.rideID);
      }
      if (struct.isSetDestination()) {
        oprot.writeString(struct.destination);
      }
      if (struct.isSetDate()) {
        oprot.writeString(struct.date);
      }
      if (struct.isSetHour()) {
        oprot.writeString(struct.hour);
      }
      if (struct.isSetNrSeats()) {
        oprot.writeI32(struct.nrSeats);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Ride struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.rideID = iprot.readI32();
        struct.setRideIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.destination = iprot.readString();
        struct.setDestinationIsSet(true);
      }
      if (incoming.get(2)) {
        struct.date = iprot.readString();
        struct.setDateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.hour = iprot.readString();
        struct.setHourIsSet(true);
      }
      if (incoming.get(4)) {
        struct.nrSeats = iprot.readI32();
        struct.setNrSeatsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

