/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Domain
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Booking : TBase
  {
    private int _bookingID;
    private int _personID;
    private int _rideID;
    private int _seatNo;

    public int BookingID
    {
      get
      {
        return _bookingID;
      }
      set
      {
        __isset.bookingID = true;
        this._bookingID = value;
      }
    }

    public int PersonID
    {
      get
      {
        return _personID;
      }
      set
      {
        __isset.personID = true;
        this._personID = value;
      }
    }

    public int RideID
    {
      get
      {
        return _rideID;
      }
      set
      {
        __isset.rideID = true;
        this._rideID = value;
      }
    }

    public int SeatNo
    {
      get
      {
        return _seatNo;
      }
      set
      {
        __isset.seatNo = true;
        this._seatNo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool bookingID;
      public bool personID;
      public bool rideID;
      public bool seatNo;
    }

    public Booking() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                BookingID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                PersonID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                RideID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                SeatNo = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Booking");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.bookingID) {
          field.Name = "bookingID";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(BookingID);
          oprot.WriteFieldEnd();
        }
        if (__isset.personID) {
          field.Name = "personID";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(PersonID);
          oprot.WriteFieldEnd();
        }
        if (__isset.rideID) {
          field.Name = "rideID";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RideID);
          oprot.WriteFieldEnd();
        }
        if (__isset.seatNo) {
          field.Name = "seatNo";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(SeatNo);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Booking(");
      bool __first = true;
      if (__isset.bookingID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("BookingID: ");
        __sb.Append(BookingID);
      }
      if (__isset.personID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PersonID: ");
        __sb.Append(PersonID);
      }
      if (__isset.rideID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RideID: ");
        __sb.Append(RideID);
      }
      if (__isset.seatNo) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SeatNo: ");
        __sb.Append(SeatNo);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
