/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-05")
public class ITransportObserver {

  public interface Iface {

    public void updateRides(java.util.List<Domain.Ride> rides) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void updateRides(java.util.List<Domain.Ride> rides, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void updateRides(java.util.List<Domain.Ride> rides) throws org.apache.thrift.TException
    {
      send_updateRides(rides);
    }

    public void send_updateRides(java.util.List<Domain.Ride> rides) throws org.apache.thrift.TException
    {
      updateRides_args args = new updateRides_args();
      args.setRides(rides);
      sendBaseOneway("updateRides", args);
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void updateRides(java.util.List<Domain.Ride> rides, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      updateRides_call method_call = new updateRides_call(rides, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class updateRides_call extends org.apache.thrift.async.TAsyncMethodCall<Void> {
      private java.util.List<Domain.Ride> rides;
      public updateRides_call(java.util.List<Domain.Ride> rides, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, true);
        this.rides = rides;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("updateRides", org.apache.thrift.protocol.TMessageType.ONEWAY, 0));
        updateRides_args args = new updateRides_args();
        args.setRides(rides);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return null;
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("updateRides", new updateRides());
      return processMap;
    }

    public static class updateRides<I extends Iface> extends org.apache.thrift.ProcessFunction<I, updateRides_args> {
      public updateRides() {
        super("updateRides");
      }

      public updateRides_args getEmptyArgsInstance() {
        return new updateRides_args();
      }

      protected boolean isOneway() {
        return true;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public org.apache.thrift.TBase getResult(I iface, updateRides_args args) throws org.apache.thrift.TException {
        iface.updateRides(args.rides);
        return null;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("updateRides", new updateRides());
      return processMap;
    }

    public static class updateRides<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, updateRides_args, Void> {
      public updateRides() {
        super("updateRides");
      }

      public updateRides_args getEmptyArgsInstance() {
        return new updateRides_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Void>() { 
          public void onComplete(Void o) {
          }
          public void onError(java.lang.Exception e) {
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
            } else {
              _LOGGER.error("Exception inside oneway handler", e);
            }
          }
        };
      }

      protected boolean isOneway() {
        return true;
      }

      public void start(I iface, updateRides_args args, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
        iface.updateRides(args.rides,resultHandler);
      }
    }

  }

  public static class updateRides_args implements org.apache.thrift.TBase<updateRides_args, updateRides_args._Fields>, java.io.Serializable, Cloneable, Comparable<updateRides_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("updateRides_args");

    private static final org.apache.thrift.protocol.TField RIDES_FIELD_DESC = new org.apache.thrift.protocol.TField("rides", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new updateRides_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new updateRides_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.List<Domain.Ride> rides; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      RIDES((short)1, "rides");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // RIDES
            return RIDES;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.RIDES, new org.apache.thrift.meta_data.FieldMetaData("rides", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Domain.Ride.class))));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(updateRides_args.class, metaDataMap);
    }

    public updateRides_args() {
    }

    public updateRides_args(
      java.util.List<Domain.Ride> rides)
    {
      this();
      this.rides = rides;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public updateRides_args(updateRides_args other) {
      if (other.isSetRides()) {
        java.util.List<Domain.Ride> __this__rides = new java.util.ArrayList<Domain.Ride>(other.rides.size());
        for (Domain.Ride other_element : other.rides) {
          __this__rides.add(new Domain.Ride(other_element));
        }
        this.rides = __this__rides;
      }
    }

    public updateRides_args deepCopy() {
      return new updateRides_args(this);
    }

    @Override
    public void clear() {
      this.rides = null;
    }

    public int getRidesSize() {
      return (this.rides == null) ? 0 : this.rides.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<Domain.Ride> getRidesIterator() {
      return (this.rides == null) ? null : this.rides.iterator();
    }

    public void addToRides(Domain.Ride elem) {
      if (this.rides == null) {
        this.rides = new java.util.ArrayList<Domain.Ride>();
      }
      this.rides.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<Domain.Ride> getRides() {
      return this.rides;
    }

    public updateRides_args setRides(@org.apache.thrift.annotation.Nullable java.util.List<Domain.Ride> rides) {
      this.rides = rides;
      return this;
    }

    public void unsetRides() {
      this.rides = null;
    }

    /** Returns true if field rides is set (has been assigned a value) and false otherwise */
    public boolean isSetRides() {
      return this.rides != null;
    }

    public void setRidesIsSet(boolean value) {
      if (!value) {
        this.rides = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case RIDES:
        if (value == null) {
          unsetRides();
        } else {
          setRides((java.util.List<Domain.Ride>)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case RIDES:
        return getRides();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case RIDES:
        return isSetRides();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof updateRides_args)
        return this.equals((updateRides_args)that);
      return false;
    }

    public boolean equals(updateRides_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_rides = true && this.isSetRides();
      boolean that_present_rides = true && that.isSetRides();
      if (this_present_rides || that_present_rides) {
        if (!(this_present_rides && that_present_rides))
          return false;
        if (!this.rides.equals(that.rides))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetRides()) ? 131071 : 524287);
      if (isSetRides())
        hashCode = hashCode * 8191 + rides.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(updateRides_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetRides()).compareTo(other.isSetRides());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRides()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rides, other.rides);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("updateRides_args(");
      boolean first = true;

      sb.append("rides:");
      if (this.rides == null) {
        sb.append("null");
      } else {
        sb.append(this.rides);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class updateRides_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public updateRides_argsStandardScheme getScheme() {
        return new updateRides_argsStandardScheme();
      }
    }

    private static class updateRides_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<updateRides_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, updateRides_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // RIDES
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.rides = new java.util.ArrayList<Domain.Ride>(_list0.size);
                  @org.apache.thrift.annotation.Nullable Domain.Ride _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = new Domain.Ride();
                    _elem1.read(iprot);
                    struct.rides.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setRidesIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, updateRides_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.rides != null) {
          oprot.writeFieldBegin(RIDES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.rides.size()));
            for (Domain.Ride _iter3 : struct.rides)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class updateRides_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public updateRides_argsTupleScheme getScheme() {
        return new updateRides_argsTupleScheme();
      }
    }

    private static class updateRides_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<updateRides_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, updateRides_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetRides()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetRides()) {
          {
            oprot.writeI32(struct.rides.size());
            for (Domain.Ride _iter4 : struct.rides)
            {
              _iter4.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, updateRides_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.rides = new java.util.ArrayList<Domain.Ride>(_list5.size);
            @org.apache.thrift.annotation.Nullable Domain.Ride _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = new Domain.Ride();
              _elem6.read(iprot);
              struct.rides.add(_elem6);
            }
          }
          struct.setRidesIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
